server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account
          predicates:
            - Path=/account/**
        - id: account-ms-service
          uri: lb://account-ms
          predicates:
            - Path=/account-ms/**
        - id: account-transfers-ms-service
          uri: lb://account-transfers-ms
          predicates:
            - Path=/account-transfers-ms/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 